export const Medias = [
  {
    sectionTitle: 'The Weird Ones',
    medias: [
      {
        hashID: 'dwr17www4g',
        slug: 'save-the-date',
        thumbnail: 'Save-the-Date.jpg',
        title: 'Save the Date',
        duration: '2:05',
        created: '3 years ago',
        comments: '2',
        plays: '497',
      },
      {
        hashID: 'yftvi822yb',
        slug: 'wistia-for-chrome',
        thumbnail: 'Wistia-for-Chrome.jpg',
        title: 'Wistia for Chrome',
        duration: '1:06',
        created: '3 years ago',
        comments: '3',
        plays: '462',
      },
      {
        hashID: 'nko75eyhfw',
        slug: 'the-business-video-barbershop-quartet',
        thumbnail: 'The-Business-Videos-Barbershop-Quartet.jpg',
        title: 'The Business Videos Barbershop Quartet',
        duration: '0:50',
        created: '3 years ago',
        comments: '3',
        plays: '561',
      },
      {
        hashID: 'tf4r23iuzk',
        slug: 'songs-about-wistia',
        thumbnail: 'Songs-About-Wistia.jpg',
        title: 'Songs About Wistia',
        duration: '1:23',
        created: '3 years ago',
        comments: '3',
        plays: '401',
      },
      {
        hashID: 'bg2qyrubpu',
        slug: 'farewell-to-the-canon-50-mark-iii',
        thumbnail: 'Farewell-to-the-Canon-5D-Mark-III.jpg',
        title: 'Farewell to the Canon 5D Mark III',
        duration: '1:06',
        created: '3 years ago',
        comments: '3',
        plays: '1K',
      },
      {
        hashID: 'pdxm7k34su',
        slug: 'dinousars-30-second-ad',
        thumbnail: 'Dinosaurs-30-Second-Ad.jpg',
        title: 'Dinosaurs 30 Second Ad',
        duration: '1:06',
        created: '3 years ago',
        comments: '3',
        plays: '1.1K',
      },
    ],
  },
  {
    sectionTitle: 'Product Launches',
    medias: [
      {
        hashID: 'e8btjs17pp',
        slug: 'the-enterprise-plan-parade',
        thumbnail: 'The-Enterprise-Plan-Parade.jpg',
        title: 'The Enterprise Plan Parade',
        duration: '1:20',
        created: '3 years ago',
        comments: '2',
        plays: '1.1K',
      },
      {
        hashID: '5lorl87lxy',
        slug: 'vulcan-wistias-new-player',
        thumbnail: 'Vulcan.jpg',
        title: "Vulcan: Wistia's New Player",
        duration: '2:31',
        created: '3 years ago',
        comments: '2',
        plays: '220',
      },
      {
        hashID: '1tm4cxja39',
        slug: 'video-in-email',
        thumbnail: 'Video-In-Email.jpg',
        title: 'Video In Email',
        duration: '0:54',
        created: '3 years ago',
        comments: '2',
        plays: '995',
      },
      {
        hashID: 'r14x7ulp7i',
        slug: 'good-account-bad-account',
        thumbnail: 'Good-Account-Bad-Account.jpg',
        title: 'Good Account Bad Account',
        duration: '3:20',
        created: '3 years ago',
        comments: '2',
        plays: '1K',
      },
    ],
  },
  {
    sectionTitle: '50 Grove Classics',
    medias: [
      {
        hashID: '2mbahxoca6',
        slug: 'lenny-delivers-video',
        thumbnail: 'Lenny-Delivers-Video.jpg',
        title: 'Lenny Delivers Video',
        duration: '0:40',
        created: '3 years ago',
        comments: '2',
        plays: '622',
      },
      {
        hashID: 'kcq5sgths9',
        slug: 'sharing-modal',
        thumbnail: 'Sharing-Modal.jpg',
        title: 'Sharing Modal',
        duration: '0:47',
        created: '3 years ago',
        comments: '2',
        plays: '472',
      },
      {
        hashID: 'yog7fz8bjk',
        slug: 'suit-up',
        thumbnail: 'Suit-Up.jpg',
        title: 'Suit Up - Get Serious About Web Video',
        duration: '0:57',
        created: '3 years ago',
        comments: '2',
        plays: '574',
      },
      {
        hashID: 'xvlj1upcg5',
        slug: 'wistia-labls-launch',
        thumbnail: 'Wistia-Labs-Launch.jpg',
        title: 'Wistia Labs Launch',
        duration: '0:58',
        created: '3 years ago',
        comments: '2',
        plays: '611',
      },
      {
        hashID: '8ygepy9xlj',
        slug: 'sent-from-my-iphone',
        thumbnail: 'Sent-from-my-iPhone.jpg',
        title: 'Sent From My iPhone',
        duration: '1:37',
        created: '3 years ago',
        comments: '2',
        plays: '708',
      },
      {
        hashID: 'tjpjd3qltf',
        slug: 'how-they-work',
        thumbnail: 'How-They-Work.jpg',
        title: 'How They Work: Zappos',
        duration: '2:47',
        created: '3 years ago',
        comments: '2',
        plays: '415',
      },
    ],
  },
];

//https://crlvideo.wistia.com/projects/d2wuk4po5m
